CREATE TABLE INVENTORY (
    ID INTEGER PRIMARY KEY,
    DATE TIMESTAMP
);

CREATE TABLE STOCK (
    ID INTEGER PRIMARY KEY,
    INVENTORY_ID INTEGER,
    PRODUCT_NAME TEXT,
    AMOUNT DECIMAL
);

CREATE SEQUENCE INVENTORY_SEQUENCE;
CREATE SEQUENCE STOCK_SEQUENCE;
