CREATE SEQUENCE MIXED_SEQUENCE;

CREATE TABLE FORK (
        ID INTEGER PRIMARY KEY,
        MEASURE DECIMAl
);

CREATE TABLE STUCK (
        ID INTEGER PRIMARY KEY,
        NAME TEXT,
        MOVER_ID INTEGER
);

CREATE TABLE MOVER (
        ID INTEGER PRIMARY KEY,
        FORK_ID INTEGER
);