CREATE SEQUENCE AUTHOR_SEQUENCE;
CREATE SEQUENCE RECIPE_SEQUENCE;
CREATE SEQUENCE INGREDIENT_SEQUENCE;

CREATE TABLE AUTHOR (
    ID INTEGER PRIMARY KEY,
    NAME TEXT
);

CREATE TABLE RECIPE (
    ID INTEGER PRIMARY KEY,
    AUTHOR_ID INTEGER,
    NAME TEXT
);

CREATE TABLE INGREDIENT (
    ID INTEGER PRIMARY KEY,
    RECIPE_ID INTEGER,
    NAME TEXT,
    AMOUNT INTEGER
);